database:
  name: quisell
  username:
  password:
  host:
  port: 5432

spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true
    url: ${spring.datasource.url}
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: postgres
    password: postgres