database:
  name: quisell
  username: postgres
  password: postgres
  host: localhost
  port: 5432

spring:
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true
    url: ${spring.datasource.url}
    user: ${database.username}
    password: ${database.password}
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}